---
sidebar: sidebar 
permalink: use/capacity-remediate-overview.html 
keywords: economic efficiency remediate, economic efficiency, capacity planning 
summary: 'Il servizio NetApp BlueXP Economic Efficiency Capacity Planning utilizza l"ai per prevedere la crescita dei dati per agevolare il processo di pianificazione.' 
---
= Esaminare e risolvere i problemi di capacità
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
La pianificazione della capacità implica l'identificazione di aree a bassa capacità nel tuo ambiente, sia attuali che previste. L'efficienza economica di BlueXP utilizza l'intelligenza artificiale per prevedere la crescita dei dati e contribuire al processo di pianificazione. Il servizio di efficienza economica identifica le aree a bassa capacità del tuo ambiente.

Utilizzando l'efficienza economica di BlueXP, è possibile raggiungere questi obiettivi:

* link:../use/capacity-review-status.html["Esaminare lo stato della pianificazione della capacità"]
* link:../use/capacity-tier-data.html["Tier cold data to cloud storage e liberare storage"]
* link:../use/capacity-reminders.html["Selezionare NO action (nessuna azione) e impostare i promemoria da controllare di nuovo"]

