---
sidebar: sidebar 
permalink: get-started/capacity-login.html 
keywords: bluexp login, capacity planning log in 
summary: 'Inizia a utilizzare l"efficienza economica di BlueXP accedendo al servizio in BlueXP.' 
---
= Accedi all'efficienza economica di BlueXP
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
Utilizzate NetApp BlueXP per accedere al servizio di efficienza economica.

Per accedere a BlueXP, puoi utilizzare le credenziali del sito di supporto NetApp oppure iscriverti per un login cloud NetApp utilizzando la tua email e una password. https://docs.netapp.com/us-en/bluexp-setup-admin/task-logging-in.html["Scopri di più sull'accesso"^].


TIP: È possibile accedere a questa funzione sia tramite l'efficienza economica di BlueXP (*Governance* > *efficienza economica* > *Tech refresh*) o tramite il consulente digitale di NetApp (*Dashboard* > *Planning widget* > *Tech refresh*).

.Fasi
. Aprire un browser Web e accedere a. https://console.bluexp.netapp.com/["Console BlueXP"^].
+
Viene visualizzata la pagina di accesso a NetApp BlueXP.

. Accedere a BlueXP.
. Dalla barra di navigazione a sinistra di BlueXP, selezionare *Governance* > *Economic Efficiency*.

