---
sidebar: sidebar 
permalink: get-started/intro.html 
keywords: how bluexp economic efficiency works, what is economic efficiency, bluexp, hardware refresh, technology refresh, capacity, forecasted capacity, storage, forecast 
summary: Il servizio di efficienza economica di BlueXP  identifica i cluster con capacità bassa attuale o prevista e offre consigli sul tiering dei dati. 
---
= Scopri l'efficienza economica di BlueXP
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
L'efficienza economica di BlueXP  valuta le tue risorse storage con una capacità bassa, attuale o prevista. Il servizio offre consigli sulle opzioni di tiering dei dati che soddisfano le tue esigenze di business.

L'efficienza economica di BlueXP può aiutarti a raggiungere i seguenti obiettivi.

*Pianificazione della capacità*

* Identificare le risorse di storage del tuo ambiente che mostrano una capacità bassa.
* Esaminare le risorse per la capacità corrente e prevista.




== Vantaggi dell'efficienza economica di BlueXP

L'efficienza economica di BlueXP offre i seguenti vantaggi:

* Identifica i sistemi che si stanno avvicinando agli eventi del ciclo di vita per aiutarti a pianificare un refresh tecnologico
* Offre consigli di un consulente fidato per affrontare problemi di capacità nel tuo ambiente
* Riduce il tempo impiegato per la pianificazione di storage aggiuntivo




== Costo

NetApp non addebita alcun costo per l'utilizzo del servizio.

Se decidi di eseguire il tiering dei dati cold allo storage cloud, dovrai controllare il tuo cloud provider per verificare i costi applicabili.



== Accesso

È possibile accedere a questa funzione sia tramite l'efficienza economica di BlueXP (*Governance* > *efficienza economica* > *Tech refresh*) o tramite il consulente digitale di NetApp (*Dashboard* > *Planning widget* > *Tech refresh*).
